DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS list;
DROP TABLE IF EXISTS item;
/*DROP TABLE IF EXISTS types_lists;
DROP TABLE IF EXISTS type;
DROP TABLE IF EXISTS today;*/

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

/*CREATE TABLE post (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
);*/

CREATE TABLE list (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created DATE NOT NULL DEFAULT CURRENT_DATE,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
);

/*
CREATE TABLE type (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);*/

CREATE TABLE item (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    date_created DATE NOT NULL DEFAULT CURRENT_DATE,
    date_due DATE NOT NULL DEFAULT CURRENT_DATE,
    description TEXT,
    listid INTEGER,
    completed INTEGER,
    FOREIGN KEY (listid) REFERENCES list (id)
);
