DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
/*DROP TABLE IF EXISTS types_lists;
DROP TABLE IF EXISTS list;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS type;
DROP TABLE IF EXISTS today;*/

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE post (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
)
/*
CREATE TABLE type (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE item (
    sl INTEGER,
    title TEXT NOT NULL,
    date_created DATE,
    date_edited  DATE,
    date_completed DATE,
    description TEXT,
    FOREIGN KEY ()
);*/
